"""users table

Revision ID: 26785fe8cc77
Revises: 64c1f07167d5
Create Date: 2021-02-15 18:27:03.048252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26785fe8cc77'
down_revision = '64c1f07167d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordine',
    sa.Column('id_ordine', sa.Integer(), nullable=False),
    sa.Column('acquisti', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['biglietto.id_ticket'], ),
    sa.PrimaryKeyConstraint('id_ordine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordine')
    # ### end Alembic commands ###
