"""users table

Revision ID: 64c1f07167d5
Revises: 94881067a29a
Create Date: 2021-02-15 11:54:52.564827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c1f07167d5'
down_revision = '94881067a29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema', sa.Column('n_posti', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinema', 'n_posti')
    # ### end Alembic commands ###
