"""users table

Revision ID: 94881067a29a
Revises: 
Create Date: 2021-02-15 11:34:49.068076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94881067a29a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('titolo', sa.String(), nullable=True),
    sa.Column('orario', sa.DateTime(), nullable=True),
    sa.Column('sold_out', sa.Boolean(), nullable=True),
    sa.Column('id_cinema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cinema'], ['cinema.id'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_evento_id_film'), 'evento', ['id_film'], unique=False)
    op.create_index(op.f('ix_evento_orario'), 'evento', ['orario'], unique=False)
    op.create_index(op.f('ix_evento_titolo'), 'evento', ['titolo'], unique=False)
    op.create_table('biglietto',
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id_evento'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_index(op.f('ix_biglietto_posto'), 'biglietto', ['posto'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biglietto_posto'), table_name='biglietto')
    op.drop_table('biglietto')
    op.drop_index(op.f('ix_evento_titolo'), table_name='evento')
    op.drop_index(op.f('ix_evento_orario'), table_name='evento')
    op.drop_index(op.f('ix_evento_id_film'), table_name='evento')
    op.drop_table('evento')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('cinema')
    # ### end Alembic commands ###
